name: task_manager_flutter
description: A clean Flutter Task Manager app using Provider + Hive (web & mobile).
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  intl: ^0.20.2
  device_preview: ^1.3.1
  # flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  drift: ^2.30.0
  sqlite3_flutter_libs: ^0.5.41
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.30.0
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
